public class Hello {
    public static void main(String[] args) {
        System.out.println("Hello, World! How are you all doing today?");
        System.out.println("Cara, eu não sei muito o que dizer sobre mim, mas podemos começar pelo meu nome, eu sou Carlos Eduardo, tenho 14 anos. Cheguei no Sesi esse ano e sou primeirista, faço o intinerário 5, cursando inofrmática para internet. Eu gosto de... MUITA coisa, muita coisa mesmo, poderia fazer uma listinha? Sim. Mas tenho preguiça então vou resumir.");
        System.out.println("Eu gosto de jogar, geralmente jogos como minecraft, roblox e outras coisas, não posso ter muita coisa no PC que tenho, por que ele é da minha irmã e ela me limitou à um jogo. Até um tempo atrás eu jogava LoL e, pra quem quiser saber, eu era main Yorick top, mas também jogava em outras lanes quem me pedisse, SOU ÓTIMO DE XAYAH ADC VIU. Enfim, eu queria poder explorar mais jogos, mas isso só quando eu tiver meu próprio PC. Quem quiser jogar um mine comigo qualquer dia, meu discord é 'Kai.#0439'.");
        System.out.println("A introdução em inglês ali, sim, sim, fui eu que escrevi. Sou autodidata em inglês e me orgulho em dizer que eu aprendi a falar jogando jogos, como o próprio minecraft, e assistindo desenhos, como Pica-Pau, Steven Universo, Apenas um Show e Hora de Aventura.");
        System.out.println("Eu sou apaixonado pela ára de programação tem já um tempo, desde e os meus 11 anos quando conheci alguns youtubers que trabalhavam com a área, desenvolvendo jogos e mods para jogos já existentes, como o próprio lindo e maravilhoso Botão Select. Esse ano conheci um youtuber gringo chamado Fundy, ele costuma fazer mods e datapacks para o minecraft, me apaixonei mesmo depois de um tempo vendo o trabalho deles.");
        System.out.println("Falando em datapacks para minecraft, eu já tentei criar um datapack para um mod chamado 'Origins', porém, como eu não tina tanta experiência foi um projeto falho, foi bom enquanto durou de qualquer forma, ksksks. Eu ia até tentar programar alguma coisinha pequena para interagir com o texto, como um enigma, mas fiquei com medo de ferrar o que eu já fiz aqui, demorei pra entender como que fazia alguma coisa.");
    }
}
